# Generated by Django 3.2.9 on 2021-11-29 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authservice', '0002_rename_permissiontype_permission_requestmethod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='description',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='permission',
            name='endpoint',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='permission',
            name='requestMethod',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='role',
            name='description',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=20),
        ),
    ]
